name: pm / release

on:
  workflow_dispatch:

jobs:
  auto:
    name: auto
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: unshallow
        run: |
          git fetch --unshallow --tags

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: setup pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.5.1

      - name: install auto
        run: |
          npm install auto @auto-it/released @auto-it/git-tag --global

      - name: copy config
        run: |
          cp ./.github/auto.json ./.autorc.json

      - name: get version bump
        id: version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=bump::$(auto version)"

      - name: bump version and release
        if: steps.version.outputs.bump != ''
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git pull --ff-only
          npm version $BUMP -m "Bump version to: %s [skip ci]"
          git push --follow-tags
          auto release --base-branch "$DEFAULT_BRANCH"
        env:
          BUMP: ${{ steps.version.outputs.bump }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
