name: pm / push

on:
  push:
    branches: [master, trunk]

jobs:
  release-drafter:
    name: release drafter
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: updating draft release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
