name: pm / release

on:
  release:
    types:
      - published

jobs:
  upload-release-assets:
    name: upload release assets
    runs-on: ubuntu-latest
    steps:
      - name: build project
        run: |
          echo "read something" > README.md
          zip --junk-paths my-artifact README.md

      - name: uploading built assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip
